### ISSUE TITLE
auth0 APIError

### ISSUE THREAD

**Issue by jay-meister** [opensessions/opensessions#464]
Getting this auth0 api error on initial page load. I have checked out Nicks latest commit `2c84513af1be24490548f515dc702aa465409864` and still getting it.

```
  name: 'APIError',
  message: 'getaddrinfo ENOTFOUND opensessions-test.eu.auth0.com opensessions-test.eu.auth0.com:443',
  statusCode: 'ENOTFOUND',
  requestInfo:
   { method: 'get',
     url: 'https://opensessions-test.eu.auth0.com/api/v2/users' },
  originalError:
   { Error: getaddrinfo ENOTFOUND opensessions-test.eu.auth0.com opensessions-test.eu.auth0.com:443
       at errnoException (dns.js:28:10)
       at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
     code: 'ENOTFOUND',
     errno: 'ENOTFOUND',
     syscall: 'getaddrinfo',
     hostname: 'opensessions-test.eu.auth0.com',
     host: 'opensessions-test.eu.auth0.com',
     port: 443,
     response: undefined } }
```

**Comment by jay-meister** [comment]
We don't know who created `opensessions-test`. I have opened a support ticket with auth0.

**Comment by lukehesluke** [comment]
I can't see an `opensessions-test` domain at all @JMurphyWeb so suspect it may have been deleted. If so, you could create a new one

**Comment by jay-meister** [comment]
Now seems to be working again. I don't know who has access to the `opensessions-test` account though.
